version: '3'
services:
  mall-product:
    build: 
      context: ./mall-product
      dockerfile: Dockerfile
    container_name: mall-product
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mall-network

  mall-order:
    build:
      context: ./mall-order
      dockerfile: Dockerfile
    container_name: mall-order
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mall-network

  mall-admin:
    build:
      context: ./mall-admin
      dockerfile: Dockerfile
    container_name: mall-admin
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mall-network

networks:
  mall-network:
    driver: bridge 