server:
  port: 8085

spring:
  application:
    name: mall-admin
  datasource:
    url: jdbc:mysql://prod-mysql:3306/mall_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  cloud:
    openfeign:
      client:
        config:
          mall-product:
            url: http://mall-product:8081

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 